version: '3.8'

services:
  xmrt_bitnet_dev:
    build:
      context: .
      dockerfile: Dockerfile
      target: builder
    ports:
      - "8080:8080"
    environment:
      - NODE_ENV=development
      - LOG_LEVEL=debug
    volumes:
      - .:/app
      - /app/node_modules  # Prevent node_modules override
    restart: unless-stopped
    command: ["./dev.sh"]
    networks:
      - xmrt-dev-network

networks:
  xmrt-dev-network:
    driver: bridge
